#!/bin/bash

if [ ! "$(grep nox /proc/cmdline)" ]
then
	if [ -x /usr/bin/X ]
	then
		if [ -e /etc/startx -a $(tty) = "/dev/tty1" ];
		then
			rm -f /etc/startx
			##STARTX
			[ -f /etc/motd ] && cat /etc/motd
		fi
	fi
fi
