Gentoo Linux LiveCD boot options - [F1 to display available kernels]

Please hit F1 to see the available kernels on this livecd.  Please note that
the -nofb counterparts to each kernel disable the framebuffer
and splash images. Additionally, the memtest86 boot option is available
to test local RAM for errors. To use memtest86, just type 'memtest86'.

There are numerous options available that can be passed to the kernel on this
command line.  You can read all of the options by checking README.txt on this
CDROM.
